sudo: false
language: node_js
#cache:
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - "6"
  - "8"

env:
  global:
    - CXX=g++-4.8
    - TWITTER_BEARER_TOKEN=123456789

matrix:
  allow_failures:
  - node_js: "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
      repo_token: ${CODECLIMATE_REPO_TOKEN}

# before_script:
#   - npm install --global snyk
#   - snyk auth ${SNYK_TOKEN}

script:
  - npm run build
  # - npm run security_check
  - npm run lint
  - npm run test
